apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: web
spec:
  containers:
    - name: myapp
      image: gcr.io/google_containers/ubuntu-slim:0.4
      command:
      - sleep
      args:
      - "1000"
    - name: collocated-pod-proxy
      image: mumoshu/kube-collocated-pod-proxy:kube-1.3.6
      ports:
        - containerPort: 8125
      env:
      - name: PORT
        value: "8125"
      - name: SELECTOR
        value: "app=dd-agent"
      - name: PROTOCOL
        value: udp
      - name: NAMESPACE
        value: kube-system
